### ISSUE TITLE
Remove hardcoded chart dimensions

### ISSUE THREAD

**Issue by 100781** [vmpowerio/chartjs-node#1]
The canvas object on line 43 of index.js contains hardcoded width and height values of 400px, overriding the ability to specify dimensions when creating a new ChartjsNode:

`<canvas id="myChart" width="400" height="400" style="width:400px;height:400px">`

Replacing the hardcoded values with `this.width` and `this.height` solves the problem.

**Comment by sedouard** [comment]
Thanks for pointing that out! Closed via https://github.com/vmpowerio/chartjs-node/pull/2. Published v1.01
