### ISSUE TITLE
Support Chart.js 2.5.0

### ISSUE THREAD

**Issue by jfeldstein** [vmpowerio/chartjs-node#17]
I am getting: `npm WARN chartjs-node@1.4.0 requires a peer of chart.js@<=2.4.* but none was installed.`

I have 2.5.0 installed. 

Why is `<=2.4.*` required? Why not `^2.4.0` which would allow upgrading until `3.0.0` ?

**Comment by sedouard** [comment]
Since I haven't tested the module on later versions of chart.js -- I don't
know if it will work. Especially after a major version change (apis can
change and so forth.) You're welcome to submit a PR if you've tested on 3.0
and can validate that.

Otherwise I'll look into doing that later next week.

**Comment by sedouard** [comment]
Closed via https://github.com/vmpowerio/chartjs-node/pull/18. You can get `chartjs-node@1.4.1` on npm.
