### ISSUE TITLE
writeImageToFile uses an unsafe writing method to confirm write complete

### ISSUE THREAD

**Issue by hparadiz** [vmpowerio/chartjs-node#21]
Please review this:
http://www.daveeddy.com/2013/03/26/synchronous-file-io-in-nodejs/

> `fs. createWriteStream ` is synchronous in the sense that it blocks the event loop while it executes. It does NOT ask the Kernel to do a synchronous write to the underlying file system.

In my use case I'm generating a chart as a png and then uploading to Slack.

Approximately 10% of the time the file hasn't actually finished writing to disk before `chartNode.writeImageToFile` has returned it's promise. This causes the file upload to fail.

The write to disk should be changed to `fs.open()` or `fs.fsync()` to make sure the file is fully written to disk before returning a promise.

Here's a test script for the issue I'm describing.
https://gist.github.com/hparadiz/c20cc3fa1cf9aba7497a7fe89594bf65

Notice line 46 which should never actually be triggered but is.

**Comment by hparadiz** [comment]
https://github.com/vmpowerio/chartjs-node/pull/22

Please try my fix

**Comment by sedouard** [comment]
Hey there!

Thanks for the PR I'll give it a look over tonight (east coast us) and get
back to you. Thanks a bunch!! 🙌🏽

**Comment by hparadiz** [comment]
No worries. Take your time. East coast here too.

travis-ci was complaining so I made a quick fix and made a new PR. Sorry for the clutter.

**Comment by hparadiz** [comment]
Solved
