### ISSUE TITLE
Blurry Images

### ISSUE THREAD

**Issue by kevindieu100** [vmpowerio/chartjs-node#25]
![chart](https://user-images.githubusercontent.com/15068047/26957421-cd5f568c-4c79-11e7-96c1-e687f32e2c1b.png)

**Comment by corsacca** [comment]
I have the same problem

**Comment by satyakrishnagorti** [comment]
yeah, same problem. has something to do with canvas.toDataURL() autoscaling the image.

**Comment by sedouard** [comment]
I believe this is an issue with `canvas` not much we can do from here
