### ISSUE TITLE
Allow custom chart types

### ISSUE THREAD

**Issue by SeanSobey** [vmpowerio/chartjs-node#31]
From what I understand it is not possible to add [custom chart types](http://www.chartjs.org/docs/latest/developers/charts.html) to chartjs-node? At least not without running JSDom separately to import the ChartJS library.

Might I suggest something like this:
```js
drawChart(configuration) {
  ...
  const Chartjs = require('chart.js');
  ...
  if (configuration.options.charts) {
    configuration.options.charts.forEach(chart => {
      Chartjs.defaults[chart.type] = chart.defaults || {};
      if (chart.baseType) {
        Chartjs.controllers[chart.type] = Chartjs.controllers[chart.baseType].extend(chart.controller);
      } else {
        Chartjs.controllers[chart.type] = Chartjs.DatasetController.extend(chart.controller);
      }
    });
  }
  ...
}
```
which can then be used like so:
```js
var myChartOptions = {
  charts: [{
    type: 'custom',
    baseType: 'bar',
    controller: {
     draw: function(ease) {},
      ...
    },
    defaults: {
      ...
    },
  }]
}
```

Would a pull request for this be accepted possibly?

**Comment by sedouard** [comment]
@SeanSobey yes absolutely 🎉. However because we don't use this functionality - we would need a test which verifies we can make custom chart types.

**Comment by SeanSobey** [comment]
Great, I have created a pull request.
