### ISSUE TITLE
Some valid configuration have no effect

### ISSUE THREAD

**Issue by AharonDror** [vmpowerio/chartjs-node#32]
I can't seem to remove the zero-line / border line of the axis.
I've tried this with several options that I thought all should work for the xAxes -> gridLines:
`
	display: false,
	drawBorder: false,
	zeroLineWidth: 0,
        zeroLineColor: 'rgba(255, 255, 255, 0)'
`
I expected any of these configurations to give me the desired result, yet none work (together or separately).

**Comment by sedouard** [comment]
Can you confirm this behavior does not reproduce in the browser?

**Comment by sedouard** [comment]
@AharonDror closing this out. Feel free to re-open once you have confirmed that this isn't the behavior in the browser
