### ISSUE TITLE
File save is not complete when the promise is resolved 

### ISSUE THREAD

**Issue by AharonDror** [vmpowerio/chartjs-node#33]
I'm using `chartNode.writeImageToFile`
When the promise is resolved the file **does** exist, but with size 0.
After less than 1 second the file is actually written (not sure exactly how long, but sleep for 1 sec works for me)

**Comment by sedouard** [comment]
Hey @AharonDror. This seems like an already fixed issue (see PR https://github.com/vmpowerio/chartjs-node/pull/23). Can you tell me which version of `chartjs-node` you installed?

**Comment by AharonDror** [comment]
Using 1.4.1

**Comment by AharonDror** [comment]
Just saw that this is fixed in latest master, but not in a release version.
Thanks for an awesome module, you can close this issue.
