### ISSUE TITLE
How to ensure destruction of chart?

### ISSUE THREAD

**Issue by eko24ive** [vmpowerio/chartjs-node#55]
Is there any way I can check that chart was successfully destroyed via `chartNode.destroy()` ?

**Comment by sedouard** [comment]
Hey @eko24ive if you take a look at the `destroy` test you can see how you can validate that:

https://github.com/vmpowerio/chartjs-node/blob/master/test/index.js#L14

**Comment by eko24ive** [comment]
Neat, thank you!
